language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t ahildreth/complex_fib_react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ahildreth/complex_fib_react-test npm test -- --coverage

after_success:
  - docker build -t ahildreth/complex_fib-multi_client ./client
  - docker build -t ahildreth/complex_fib-multi_nginx ./nginx
  - docker build -t ahildreth/complex_fib-multi_server ./server
  - docker build -t ahildreth/complex_fib-multi_worker ./worker
  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push ahildreth/complex_fib-multi_client
  - docker push ahildreth/complex_fib-multi_nginx
  - docker push ahildreth/complex_fib-multi_server
  - docker push ahildreth/complex_fib-multi_worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "Fibonacci-multi"
  env: "Fibonaccimulti-env"
  bucket_name: "elasticbeanstalk-eu-west-1-477122900110"
  bucket_path: "Fibonacci-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY